export enum Route {
  GARAGE = 'garage',
  WINNERS = 'winners',
}

export enum CarModel {
  'Model 3' = 'Model 3',
  'Model S' = 'Model S',
  'Model X' = 'Model X',
  'Model Y' = 'Model Y',
  'Roadster' = 'Roadster',
  'Cybertruck' = 'Cybertruck',
  'Bolt EV' = 'Bolt EV',
  'I-Pace' = 'I-Pace',
  'Kona Electric' = 'Kona Electric',
  'Taycan Turbo' = 'Taycan Turbo',
  'Taycan Turbo S' = 'Taycan Turbo S',
  'e-Golf' = 'e-Golf',
  'Soul Electric' = 'Soul Electric',
  'e6' = 'e6',
  'Leaf' = 'Leaf',
  'Zoe' = 'Zoe',
  'i3' = 'i3',
  'dolphin' = 'dolphin',
  'eQ' = 'eQ',
}
export enum CarBrand {
  'Tesla' = 'Tesla',
  'Chevrolet' = 'Chevrolet',
  'Hyundai' = 'Hyundai',
  'Kia' = 'Kia',
  'Jaguar' = 'Jaguar',
  'Porche' = 'Porche',
  'BYD' = 'BYD',
  'Volkswagen' = 'Volkswagen',
  'Nissan' = 'Nissan',
  'Renault' = 'Renault',
  'Chery' = 'Chery',
  'BMW' = 'BMW',
}
